// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("fluentforwardexporter")
	ScopeName = "github.com/axoflow/fluentforwardexporter"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
